apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-youtube
  template:
    metadata:
      labels:
        app: my-youtube
    spec:
      containers:
        - name: my-youtube
          image: dilipopseng/youtube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-youtube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
