apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: dilipopseng/youtube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: youtube-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
