apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: devops5511/youtube2.0:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
