name: Youtube CI/CD Pipeline
permissions:
  security-events: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code From Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setuping Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d /opt
          echo "/opt/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH
      - name: Run SonarQube Scanner with Debugging
        run: |
          sonar-scanner \
            -Dsonar.projectKey=dilipopseng_youtube \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.verbose=true
