name: Matrix Youtube CI/CD Pipeline
permissions:
  security-events: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 16, 12]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Code From Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Up Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Set Image Tag from Commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Docker Image
        run: docker build -t devops5511/tictacapp:${IMAGE_TAG} .
      - name: Run Trivy Docker Image Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL devops5511/tictacapp:${IMAGE_TAG} || true
      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push devops5511/tictacapp:${IMAGE_TAG}
      - name: Replace image name in Kubernetes manifest
        run: |-
          sed -i "s|image: devops5511/tictacapp:.*|image: devops5511/tictacapp:${IMAGE_TAG}|g" kube/deployment.yml
